### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by s1204IT**
If you really want to optimize this app to the max, you need to do the following:
- Remove and Disable **AndroidX**
  - This is the biggest pressure point.
- Convert **Kotlin to Java**
  - Even if the operation is exactly the same, the compression rate increases significantly just by writing it in Kotlin.
  - This simply boils down to a question of prioritizing developers or users.
  - Since it will ultimately be compiled in Java, it is obviously better to write it in Java if size is a priority.

### CODE REVIEW

**Comment by s1204IT** [comment]
@Saranomy 
Please add commits up to **2.0.3**.

**Comment by Saranomy** [comment]
Hi, thanks for the PR. I like your suggestions to convert it to Java. I will try to make it smaller and update the repo to the production version. Thank you so much for your feedback.

**Comment by s1204IT** [comment]
Once this request was made, it was mainly code optimizations that made the icons much lighter in terms of resources.

**Comment by Saranomy** [comment]
I will merge it. But for your information, this current project is very old and does not match the live version. I will replace most of the code later with the newer version. Thanks

**Pull request merged**
